# only run manually
on: workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up docker-buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push container image
        run: |
          target_image_repo="ghcr.io/${{ github.actor }}/lxconsole-oci"
          ./build.sh ${target_image_repo}

          lxconsole_target_image=$(cat .lxconsole_target_image)
          docker push ${lxconsole_target_image}
